version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: forum-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres_data: 
  redis: